type: Multiplication
desc: This task takes a number and a factor and multiplies them together using a "multiplier" device.

devices:
  multiplier:
    type: multiplier

input_parameters:
  number:
    type: int
    unit: none
    desc: The number to multiply.
  factor:
    type: int
    unit: none
    desc: The factor to multiply the number by.

output_parameters:
  in_number:
    type: int
    unit: none
    desc: The number to multiply that was given as input.
  product:
    type: int
    unit: none
    desc: The product of the number and the factor.
